application: ericdanielfournier
version: 1
runtime: go
api_version: go1

handlers:
- url: /(.*\.(otf|wotf|woff|ttf|svg|eot|php|pdf|gif|png|jpg|jpeg|ico|js|css|map))
  static_files: \1
  upload: (.*\.(otf|wotf|woff|ttf|svg|eot|php|pdf|gif|png|jpg|jpeg|ico|js|css|map))
  
- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: _go_app