application: ericdanielfournier
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(otf|wotf|ttf|svg|eot|php|pdf|gif|png|jpg|jpeg|ico|js|css))
  static_files: \1
  upload: (.*\.(otf|wotf|ttf|svg|eot|php|pdf|gif|png|jpg|jpeg|ico|js|css))
  
- url: /
  static_files: index.html
  upload: index.html

- url: .*
  script: main.application