baseurl = "https://www.ericdfournier.com"
title = "Eric Daniel Fournier"

theme = "hugo-coder"

languagecode = "en"

paginate = 100
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Eric Daniel Fournier"
    description = "Eric Daniel Fournier's personal website"
    keywords = "scientist, environment, data"
    info = "Environmental Scientist"
    avatarurl = "images/avatar.png"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ericdfournier/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/eric-fournier-17b26324/"
[[params.social]]
	name = "Google"
	icon = "fab fa-google"
	weight = 3
	url = "https://scholar.google.com/citations?user=GVp4mQcAAAAJ&hl=en"
[[params.social]]
	name = "Gitlab"
	icon = "fab fa-gitlab"
	weight = 4
	url = "https://gitlab.com/ericdfournier/"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Papers"
    weight = 2
    url  = "/papers/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Eric Daniel Fournier"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Eric Daniel Fournier"
        info = "Environmental Scientist"
        description = "Eric Daniel Fournier's personal website"
        keywords = "scientist, environment, data"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Papers"
        weight = 2
        url = "/papers/"
		
        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"
		
        [[languages.en.menu.main]]
        name = "Contact"
        weight = 4
        url = "/contact/"
