application: ericdanielfournier
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(pdf|gif|png|jpg|jpeg|ico|js|css))
  static_files: \1
  upload: (.*\.(pdf|gif|png|jpg|jpeg|ico|js|css))

- url: /.*
  script: main.py